package io.github.iso53.castiel.model;

/**
 * One LLM tool call, as shown in the chat and replayed as conversation history.
 *
 * @param id        Tool call id assigned by the harness when missing from the provider.
 * @param name      Tool name (e.g. {@code read_file}).
 * @param arguments Raw JSON arguments generated by the model.
 * @param result    Text returned by the tool execution.
 */
public record ToolCallPayload(String id, String name, String arguments, String result) {
	public ToolCallPayload {
		id = id == null ? "" : id;
		name = name == null ? "" : name;
		arguments = arguments == null ? "" : arguments;
		result = result == null ? "" : result;
	}
}
